openapi: 3.0.1
info:
  title: monster-cockatrice
  x-cortex-tag: monster-cockatrice
  x-cortex-custom-metadata:
    alignment: lawful-neutral
    type: celestial
    challenge_rating: 27
    legendary: false
    armor_class: 19
    hit_points: 95
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-cockatrice
      alias: github-token-test
